spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test.h2
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: password
  jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
        naming:
          strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      show-sql: true
  h2:
    console:
      enabled: true
      path: /console